version: '3.5'
services:
    php:
        container_name: php
        build: docker/php
        ports:
            - 9000:9000
        links:
            - db
        volumes:
            - .:/var/www/html
            - ./docker/php/logs:/var/www/app/var/logs
        depends_on:
            - db
        environment:
            - DB_HOST=localhost
            - DB_PORT=3306
            - DB_NAME=name
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_ROOT_PASSWORD=root
    server:
        container_name: nginx
        image: nginx:alpine
        ports:
            - 8080:80
        links:
            - php
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
    db:
        container_name: mysql
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
