version: '2'

services:

    web:
        container_name: myWeb
        build: docker/web
        ports:
            - 8080:80
        links:
            - mariadb
        volumes:
            - ./app:/var/www/html
            - ./var/logs/php:/var/www/app/var/logs

    mariadb:
        container_name: myMariaDB
        image: mariadb:10.3.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./var/mariadb:/var/lib/mysql