version: '3.5'
services:
    web:
        container_name: web
        build: docker/web
        ports:
            - 8080:80
        links:
            - db
        volumes:
            - .:/var/www/html
            - ./docker/php/logs:/var/www/app/var/logs
        depends_on:
            - db
        environment:
            - DB_HOST=localhost
            - DB_PORT=3306
            - DB_NAME=name
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_ROOT_PASSWORD=root
    db:
        container_name: mysql
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
